### ISSUE TITLE
Is there a way to ignore certificate validation when connecting to management service?

### ISSUE THREAD

**Issue by guojianwei001** [EasyNetQ/EasyNetQ.Management.Client#101]
The platform is .net core 2.1. I meet a failure connecting to rabbitMq management service. It says "cann't establish ssl connection". After searching some posts, I knows it has certificate validation issue. One solution is to specify the _**ServerCertificateCustomValidationCallback**_ parameter when creating HttpClientHandler as follow:

var httpClient = new HttpClient(new HttpClientHandler
            {
                Credentials = new NetworkCredential(username, password),
                ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
            })

But now ManagementClient doesn't provide any input parameter or property to handle this. Any ideas?
Thanks a lot.

**Comment by Pliner** [comment]
Hi @guojianwei001,

It seems there is not way to do it now. 

But we can pass validation callback to constructor, but may be it's better to pass `HttpClientHandler`  `Action<HttpClientHandler>` like it was done in [ConsulDotNet](https://github.com/PlayFab/consuldotnet/blob/master/Consul/Client.cs#L626).

@guojianwei001 @luigiberrettini What do you think?

**Comment by guojianwei001** [comment]
Hi @Pliner,

Thanks a lot for your quick reply. It is exactly what I think. Both two solutions are OK with me. It seems that HttpClientHandler Action<HttpClientHandler>are more flexible. 

cc @luigiberrettini

**Comment by luigiberrettini** [comment]
I agree that using an `Action<HttpClientHandler>` would be more flexible and futue proof 👍

**Comment by Pliner** [comment]
Thanks @guojianwei001, @luigiberrettini!

ASAP I will create the constructor which will be able to configure `HttpClientHandler`.

**Comment by WadeTheFade** [comment]
Ran into this last week. Any movement on this? 

Our rabbitmq cluster is in the production environment so its lower "domains" aren't secure.

**Comment by snijhof** [comment]
I also ran into this problem, we have now created a workaround with reflection, would be nice to use the `Action<HttpClientHandler>`. So we can remove our workaround.

**Comment by zidad** [comment]
Hi Sjoerd, @snijhof, are you willing to send a PR to fix this?

**Comment by Pliner** [comment]
PR was fixed in https://www.nuget.org/packages/EasyNetQ.Management.Client/1.3.0

**Comment by WadeTheFade** [comment]
Thank you for this. Here is a use case for those that run into this as well:

```
var clientHandler = new Action<HttpClientHandler>(handler =>
{
    handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true;
});

var client = new ManagementClient(host, name, pass, ssl: true, handlerConfigurator: clientHandler)
```

**Comment by alexandrudragan0** [comment]
Shortcircuiting the certificate validation can also be made using the `ConnectionConfiguration`. Example:

```c#
        var connectionConfiguration = new ConnectionConfiguration
        {
            Hosts = config.Hosts,
            Port = config.Port,
            VirtualHost = config.VirtualHost,
            UserName = string.Empty,
            PublisherConfirms = config.PublisherConfirms
        };
        connectionConfiguration.Ssl.Enabled = true;
        connectionConfiguration.Ssl.ServerName = config.Hosts[0].Host;
        connectionConfiguration.Ssl.CertificateValidationCallback = (sender, certificate, chain, errors) => { return true; };
```
