### ISSUE TITLE
Add support for manual ack

### ISSUE THREAD

**Issue by Bykiev** [EasyNetQ/EasyNetQ.Management.Client#116]
Please, add support for manual message acknowledge

**Comment by Pliner** [comment]
https://rawcdn.githack.com/rabbitmq/rabbitmq-server/v3.11.5/deps/rabbitmq_management/priv/www/api/index.html

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/664889/209465340-405e2ac2-d474-41d8-87b8-180ceef2f311.png">

It seems there is no way to manual acknowledge a message.
