### ISSUE TITLE
JSON integer is too large or small for an Int32

### ISSUE THREAD

**Issue by MaximShifrin** [EasyNetQ/EasyNetQ.Management.Client#118]
Hi
I use Assembly EasyNetQ.Management.Client, Version=0.47.12.38, Culture=neutral, PublicKeyToken=null

when try to get Queue.Messages , get the error : Newtonsoft.Json.JsonReaderException: 'JSON integer 2277968072 is too large or small for an Int32. Path '[2].memory', line 1, position 2430.'

i see that the Messages property declared as int

namespace EasyNetQ.Management.Client.Model
{
public class Queue
{
public Queue();

    public string Node { get; set; }
    public Arguments Arguments { get; set; }
    public bool AutoDelete { get; set; }
    public bool Durable { get; set; }
    public string Vhost { get; set; }
    public string Name { get; set; }
    public List<object> ConsumerDetails { get; set; }
    public BackingQueueStatus BackingQueueStatus { get; set; }
    public int ActiveConsumers { get; set; }
    public int Consumers { get; set; }
    public int Messages { get; set; }
    public int MessagesUnacknowledged { get; set; }
    public int MessagesReady { get; set; }
    public string ExclusiveConsumerTag { get; set; }
    public string Policy { get; set; }
    public string IdleSince { get; set; }
    public int Memory { get; set; }
    public IEnumerable<string> SlaveNodes { get; set; }
    public IEnumerable<string> SynchronisedSlaveNodes { get; set; }
}
}

command that I use is

return managementClient.GetQueues()
.Where(q => q.Vhost == configuration.VirtualHost)
.Select(s => new QueueStats
{
Name = s.Name,
Messages = s.Messages
});

do you have fix for messages, suppose it must be long to not fall ?

**Comment by zidad** [comment]
Can you please check with the most recent version of EasyNetQ.Management.Client?

**Comment by MaximShifrin** [comment]
I tried to use the new version, but its create problem for object ManagementClient. in new version its not contains method GetQueues() , but yes contains only GetQueuesAsync() that bring task of ienumerable. this is a problem because i can change only my projects, by this dll in use in projects of another teams and it will cause to build fail in their projects.

**Comment by zidad** [comment]
Hi Maxim,

Sorry, but I don't see a way we can fix this without you updating the library in your projects. You can try building a custom version in which you change 'int' to 'long', but I suspect you'll run into the same incompatibility between your libraries.
