### ISSUE TITLE
NuGet API key has expired

### ISSUE THREAD

**Issue by mikehadlow** [EasyNetQ/EasyNetQ.Management.Client#123]
Build error when trying to create a new release is due to the non renewed NuGet API key:
`The specified API key is invalid, has expired, or does not have permission to access the specified package.`

See PR #122 for the discussion around this.

**Comment by zidad** [comment]
I think we can copy the one for the EasyNetQ repo

**Comment by zidad** [comment]
Oh I created a PR in may already but it was never approved https://github.com/EasyNetQ/EasyNetQ.Management.Client/pull/117

**Comment by mikehadlow** [comment]
Cool, thanks @zidad.

**Comment by zidad** [comment]
Not sure how I can now trigger the build again. let me check.
