### ISSUE TITLE
Add missing Policy setting ha-sync-batch-size

### ISSUE THREAD

**Issue by ArgTang** [EasyNetQ/EasyNetQ.Management.Client#125]
`ha-sync-batch-size` option is missing in the PolicyDefinition object
https://www.rabbitmq.com/ha.html#batch-sync

To optimize mirroring on clustered rabbitmq's, it would be nice to change the default

**Comment by zidadrtl** [comment]
Hi @ArgTang, thanks! Are you willing to create a PR for this?

**Comment by zidad** [comment]
Hi @ArgTang, thanks! Are you willing to create a PR for this?
