### ISSUE TITLE
Bug: Url with path prefix throws an regex error

### ISSUE THREAD

**Issue by stpag-cv** [EasyNetQ/EasyNetQ.Management.Client#131]
Hi,

the management api is usually available at scheme://host:port/api/...
But it is also desirable (and possible) to set a different path (e.g. for reverse proxy scenarios).
This is supported by [RabbitMQs "path prefix" option](https://www.rabbitmq.com/management.html#path-prefix). 

Unfortunately EasyNetQ does not support it, see [ManagementClient](https://github.com/EasyNetQ/EasyNetQ.Management.Client/blob/16e51dfd1e744363df2efc45de70edca491f40f5/Source/EasyNetQ.Management.Client/ManagementClient.cs#L784):
```csharp
var uri = new Uri($"{HostUrl}:{PortNumber}/api/{path}{query ?? string.Empty}");
```

Using this code snippet also throws an ArgumentException of "hostUrl is illegal":
```csharp
var initial = new ManagementClient("http://localhost/management/", "guest", "guest");
```

The solution for this may be straight forward: accept a valid url (including scheme, host, port, path and query parameters) in class ManagementClient and inject the REST api + new query parameters required for the rest call.

This way, the api can be fine tuned with all available options and it may also be possible to tweak the api calls in the future to circumvent a breaking api change in rabbitmq.

Best
stpag-cv

**Comment by zidadrtl** [comment]
I think that would be a nice addition if implemented with backwards compatibility, are you willing to create a PR for this?
