### ISSUE TITLE
Trying to create a shovel results in a HTTP 400 BadRequest

### ISSUE THREAD

**Issue by bacobart** [EasyNetQ/EasyNetQ.Management.Client#142]
Trying to create a shovel results in a http 400 error. Reverting https://github.com/EasyNetQ/EasyNetQ.Management.Client/commit/12f949fdf1fb94d9088261e0017d47cb3f17c59a solves the issue. This happens with version 1.3.0.

```
	var client = new ManagementClient(...);
	
	var shovel = new ParameterShovelValue
	{
...
	};
		
	var parameter = new Parameter 
	{
		Component = "shovel",
		Name = "test",
		Value = shovel,
		Vhost = "/"
	};
	
	client.CreateParameter(parameter);

```

Related: #35

**Comment by hank-scorpio** [comment]
I'm having this issue too, is there any workaround for this?

**Comment by hank-scorpio** [comment]
One workaround is to wrap the `ParameterShovelValue` in a dummy object to restore the original behavior until this is fixed:
```
var parameter = new Parameter 
{
        ...
	Value = new { value = shovel },
        ...
};
```

**Comment by Pliner** [comment]
Hi @bacobart @hank-scorpio,

Feel free to create PR to fix this issue. Thanks.
