### ISSUE TITLE
ManagementClient functions are very slow in .Net Core

### ISSUE THREAD

**Issue by theCstokes** [EasyNetQ/EasyNetQ.Management.Client#149]
ManagementClient.CreateExchangeAsync is 9 times slower when running in .net core after upgrading from .net framework.

**Comment by Pliner** [comment]
https://github.com/EasyNetQ/EasyNetQ/issues/1225

**Comment by Pliner** [comment]
I do believe that the root cause was here https://github.com/EasyNetQ/EasyNetQ.Management.Client/commit/d08594631a769ad5fbf3c8e04b1018efbe319a09
