### ISSUE TITLE
Allow custom exchange types (for delayed-message-exchange plugin)

### ISSUE THREAD

**Issue by biiiipy** [EasyNetQ/EasyNetQ.Management.Client#16]
By design EasyNetQ throws exception, when trying to set a custom exchange type:
```Unknown exchange type 'x-delayed-message', expected one of direct, topic, fanout, headers```
The problem is with this first party RabbitMQ plugin that needs a custom exchange type - https://github.com/rabbitmq/rabbitmq-delayed-message-exchange

There should probably be a way to add custom exchange types to the predefined list in ```ExchangeInfo.cs``` class.

As a workaround, I'm overriding the Type with reflection:
```exchangeInfo.GetType().GetProperty(nameof(exchangeInfo.Type)).SetValue(exchangeInfo, "x-delayed-message");```

**Comment by Pliner** [comment]
Hi @biiiipy,
Thank you for reporting an issue. At least, I will add support of "x-delayed-exchange.

**Comment by biiiipy** [comment]
If it's ok to just add it to the predefined list, I've created a PR https://github.com/EasyNetQ/EasyNetQ.Management.Client/pull/17

**Comment by biiiipy** [comment]
Merged PR https://github.com/EasyNetQ/EasyNetQ.Management.Client/pull/17
