### ISSUE TITLE
Not working with CloudAMQP

### ISSUE THREAD

**Issue by BluePositive** [EasyNetQ/EasyNetQ.Management.Client#166]
### Problem
The Management API doesn't work with [CloudAMQP](https://www.cloudamqp.com/) (a hosted RabbitMQ service). 

### Reason
The reason is that when making the request the port is appended to the URI see [ManagementClient](https://github.com/EasyNetQ/EasyNetQ.Management.Client/blob/46c0f10459924c2b65cc0c8a0fe4e75d727978af/Source/EasyNetQ.Management.Client/ManagementClient.cs#L731) however, CloudAMQP does not allow to specify the port.

### Potential Solution 
Add an optional UsePort flag to the ManagementClient constructor with the default value set to true, Then use this flag in the CreateRequestForPath method to determine if to append the port or not.

**Comment by Pliner** [comment]
https://www.nuget.org/packages/EasyNetQ.Management.Client/2.0.0-beta7

**Comment by BluePositive** [comment]
> https://www.nuget.org/packages/EasyNetQ.Management.Client/2.0.0-beta7

Thanks!
