### ISSUE TITLE
How do Set portnumber and ssl in new api version?

### ISSUE THREAD

**Issue by MohMehrnia** [EasyNetQ/EasyNetQ.Management.Client#223]
How do Set portnumber and ssl in new api version?

**Comment by Pliner** [comment]
Hey @MohMehrnia,

Could you elaborate your question slightly by providing an example which doesn't work? 

PS In the new version, old constructor is still available, but marked as obsolete.

**Comment by MohMehrnia** [comment]
> Hey @MohMehrnia,
> 
> Could you elaborate your question slightly by providing an example which doesn't work? 
> 
> PS In the new version, old constructor is still available, but marked as obsolete.

I can not set ssl and port in new construction

**Comment by Pliner** [comment]
> > Hey @MohMehrnia,
> > Could you elaborate your question slightly by providing an example which doesn't work?
> > PS In the new version, old constructor is still available, but marked as obsolete.
> 
> I can not set ssl and port in new construction

Please, provide a short snippet with example using old constructor, then I will be able to help.

**Comment by MohMehrnia** [comment]
var management = new ManagementClient(
                $"https://{ConstantsProperties.HName}",
                ConstantsProperties.UName,
                Utils.ConvertSecureStringToString(ConstantsProperties.PWD),
                portNumber: 15671,
                ssl: true);

**Comment by Pliner** [comment]
> ```
> var management = new ManagementClient(
>                 $"https://{ConstantsProperties.HName}",
>                 ConstantsProperties.UName,
>                 Utils.ConvertSecureStringToString(ConstantsProperties.PWD),
>                 portNumber: 15671,
>                 ssl: true);
> ```
> 
> 
>      
>   
> 
> in new api i can not found nd method for enable ssl and portnumber

Thanks.

> ssl: true

This option only appends `https://` to hostname if it is not specified.

In your example you could just do the following:

```
var management = new ManagementClient(
                new Uri($"https://{ConstantsProperties.HName}:15671"),
                ConstantsProperties.UName,
                Utils.ConvertSecureStringToString(ConstantsProperties.PWD)
);
```
