### ISSUE TITLE
target_ram_count is a number (floating point) that can also get a string value "infinity"

### ISSUE THREAD

**Issue by inikulshin** [EasyNetQ/EasyNetQ.Management.Client#260]
It also makes sense that a field named "..._count" is a number.

I got the following exception from `EasyNetQ.Management.Client.ManagementClient.GetQueues()` (packages EasyNetQ.Management.Client.2.0.0, System.Text.Json.7.0.2, RabbitMQ 3.10.8)

`System.Text.Json.JsonException: 'The JSON value could not be converted to EasyNetQ.Management.Client.Model.BackingQueueStatus. Path: $[0].backing_queue_status.target_ram_count | LineNumber: 0 | BytePositionInLine: 341.`

`InvalidOperationException: Cannot get the value of a token type 'Number' as a string.`

By the way, where can I find an information about which RabbitMQ versions are supported? Minimum? Maximum? I know they make breaking changes time to time.

**Comment by inikulshin** [comment]
Here is the sample of returned Json:

  "backing_queue_status": {
      "avg_ack_egress_rate": 0,
      "avg_ack_ingress_rate": 0,
      "avg_egress_rate": 0,
      "avg_ingress_rate": 0,
      "delta": [
        "delta",
        "undefined",
        0,
        0,
        "undefined"
      ],
      "len": 0,
      "mode": "default",
      "next_deliver_seq_id": 0,
      "next_seq_id": 0,
      "q1": 0,
      "q2": 0,
      "q3": 0,
      "q4": 0,
      **"target_ram_count": 0,**
      "version": 1
    },

**Comment by kevenpoulincanam** [comment]
Hi, the fix has not been part of a release yet. We are facing this exception in production since we've upgraded to version 2.0.0. 

Would it be possible to release a new version that include this fix?

Thanks

**Comment by zidad** [comment]
@kevenpoulincanam sorry for the delay I created a new release, can you check if this one works for you? https://www.nuget.org/packages/EasyNetQ.Management.Client/2.2.0

**Comment by inikulshin** [comment]
@zidad I think version `2.2.0` is very wrong, it must be `3.0.0`, must be higher than all the prerelease versions.

**Comment by zidad** [comment]
Ah check I saw the last failed build was 2.20 and the last release 2.0.0 that's why... let me create a new one

**Comment by kevenpoulincanam** [comment]
Many thanks. The error is gone :)
