### ISSUE TITLE
Support slashes in Exchange/Queue names

### ISSUE THREAD

**Issue by jp7677** [EasyNetQ/EasyNetQ.Management.Client#27]
Hello there,

RabbitMq does allow slashes ('/') in Exchange and Queue names. When using the management client I successfully retrieve such an Exchange when asking for all Exchanges, but deleting an Exchange results in a 404/Not found exception. It would be nice if that could be fixed.

Regards and keep up the good work!

PS: Looking at the code I guess it is just an addition to the SanitiseName method in [https://github.com/EasyNetQ/EasyNetQ.Management.Client/blob/master/Source/EasyNetQ.Management.Client/ManagementClient.cs].

**Comment by micdenny** [comment]
We are happy to receive a pull request from you if you want to give a try on that
