### ISSUE TITLE
Can't create shovels since 0.48.21.0

### ISSUE THREAD

**Issue by inikulshin** [EasyNetQ/EasyNetQ.Management.Client#35]
After [this commit](https://github.com/EasyNetQ/EasyNetQ.Management.Client/commit/12f949fdf1fb94d9088261e0017d47cb3f17c59a) I can't create shovels anymore.

Reverting the change (using `parameter` instead of `parameter.Value`) works for me.

I use new ParameterShovelValue class (in CLR code, but I'm sure it is not the problem):

```
Parameter ^ parameter = gcnew Parameter();
parameter->Component = gcnew String("shovel");
parameter->Vhost = gcnew String("/");
parameter->Name = gcnew String(name.c_str());
ParameterShovelValue ^ Value = gcnew ParameterShovelValue();
// ... init src/dest
parameter->Value = Value;

managementClient->CreateParameter(parameter);
```

**Comment by luigiberrettini** [comment]
Can you check please if it is still happening?
