### ISSUE TITLE
CreateRequestForPath fails running on Mono 4.6.0.245

### ISSUE THREAD

**Issue by minuskel** [EasyNetQ/EasyNetQ.Management.Client#37]
After switching from Mono 3.2.8 to 4.6.0.245 our application (running on Debian) always failed by throwing an exception with the message "Could not resolve path field". Some research showed, that the code
`var pathField = typeof(Uri).GetField ("path", BindingFlags.Instance | BindingFlags.NonPublic);`
always results in the value `null` for variable `pathField`.
It seems there is no private field `path` in the class `Uri` anymore in never versions of the Mono framework.

**Comment by micdenny** [comment]
I have the same problem porting this piece of code in net core #34, this mean that while porting net core I will fix also this, please be patient because I don't have so many time and a lot of work to do in ENQ ecosystem and outside.

**Comment by luigiberrettini** [comment]
Closing because Mono is now no more supported: we switched to .NET core and therefore have cross-platform support
