### ISSUE TITLE
DeleteBinding between 2 exchanges fails

### ISSUE THREAD

**Issue by inikulshin** [EasyNetQ/EasyNetQ.Management.Client#43]
It uses "bindings/{0}/e/{1}/**q**/{2}/{3}" format regardless actual binding's DestinationType

**Comment by zidad** [comment]
👍 thanks for reporting

**Comment by inikulshin** [comment]
Also, all names, should be "escaped" (with SanitiseName()?) in DeleteBinding and **many**, **many** others.

This change is not complete:

// 0.50.2.0 Escape / with %2f for exchange and queue names

**Comment by micdenny** [comment]
thanks to @joostas now we have a PR for this #43
