### ISSUE TITLE
How to use IsAlive?

### ISSUE THREAD

**Issue by ghost** [EasyNetQ/EasyNetQ.Management.Client#44]
The IsAlive call in the sample code fails because aliveness-test  can only be invoked by users with either the _administrator_ or _management_ tags.  Unfortunately the Tags property on UserInfo is read-only, and it only seems to be used by ChangeUserPassword -- which preserves them. 
 
Creating a user through the client tool wipes out the tags on the existing user -- confirmed by visiting the management console.

This informs you about the management tag:

curl -i http://myUser:myPassword@localhost:15672/api/aliveness-test/my-virtual-host

**Comment by alexmg** [comment]
There is an `AddTag` method on the `UserInfo` class that can be used to add the required tags before creating the user.

```
// next create a user for that virutal host
var userInfo = new UserInfo("myUser", "myPassword").AddTag("administrator");
var user = initial.CreateUser(userInfo);
```
