### ISSUE TITLE
Create user using password hash.

### ISSUE THREAD

**Issue by joostas** [EasyNetQ/EasyNetQ.Management.Client#51]
Currently it is possible to create new user using username and password pair.
According [RabbitMQ Management HTTP API documentation](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_12/priv/www/api/index.html) there is also possibility to create new user using hashed password:

> An individual user. To PUT a user, you will need a body looking something like this:
> {"password":"secret","tags":"administrator"}
> or:
> {"password_hash":"2lmoth8l4H0DViLaK9Fxi6l9ds8=", "tags":"administrator"}

**Comment by zidad** [comment]
I'm going to close this issue ok? unfortunately we need some work to update to VS2017 still before we can do a stable release
