### ISSUE TITLE
Cannot set publish "headers" property

### ISSUE THREAD

**Issue by garie** [EasyNetQ/EasyNetQ.Management.Client#56]
The `publish` command expects headers to be an object rather than a string. The following request is valid in Postman:

POST `http://localhost:31101/api/exchanges/%2F/myroute/publish`
Body:
```
{
	"properties":{
		"headers": {"context": "{}"},
		"ProtocolClassName": "basic"
	},
	"routing_key":"myroutingkey",
	"payload": "{}",
	"payload_encoding":"string"
}
```

Setting the `headers` property to any string causes a 500 error from RabbitMQ. `PublishInfo.Properties` is a `Dictionary<string, string>`, so it is impossible to pass headers to a publish request.

**Comment by AnthonyMastrean** [comment]
This doesn't appear to be in a nuget.org release yet, is there a timeline?
