### ISSUE TITLE
GetMessagesFromQueue fails with "Bad Request"

### ISSUE THREAD

**Issue by poteb** [EasyNetQ/EasyNetQ.Management.Client#62]
RabbitMQ Server 3.7.0
EasyNetQ.Management.Client 0.51.3.116

`var messages = this.client.GetMessagesFromQueue(myQueue, new GetMessagesCriteria(1, true));`

This code fails with a "Bad Request"
When the query is run from Postman I get the reason code key_missing: ackmode
So I modify my query body from
`{"count":1,"requeue":true,"encoding":"auto"}`
(which is was EasyNetQ is sending)
to
`{"count":1,"requeue":true,"encoding":"auto","ackmode":"ack_requeue_true"}`
and then it works.

**Comment by poteb** [comment]
I'm not sure about the history of requeue in RabbitMQ since I'm pretty new to it, but maybe it got changed recently from a true/false param to the 4 values that can be set on ackmode?

**Comment by slam02** [comment]
Hi,
I'm having the same problem.

RabbitMQ Server 3.7.3
EasyNetQ.Management.Client 0.51.3.116

I'm interested in having to issue resolved too.

Is there any timeline on when the fix is going to be available on Nuget?

Thank you.

**Comment by PascalN2** [comment]
I'm also having the same problem.  
Would it be possible to have someone look at the PR from poteb?

Thank you!
@luigiberrettini 
@mikehadlow

**Comment by micdenny** [comment]
I'm on it, hold on

**Comment by micdenny** [comment]
done, new package: https://www.nuget.org/packages/EasyNetQ.Management.Client/0.52.0.188

**Comment by luigiberrettini** [comment]
This issue was not a bug but a feature request to support the breaking changes introduced with https://github.com/rabbitmq/rabbitmq-management/issues/68

Unfortunately the PR merge means this library is no more compatible with Management APIs before 3.7.x 😢
