### ISSUE TITLE
.NET Standard release?

### ISSUE THREAD

**Issue by CasperSJ** [EasyNetQ/EasyNetQ.Management.Client#64]
From the looks of the closed issues and source code it appears that Management.Client has been ported, but still not released. Has it been released somewhere else? Or is there still work to be done before it can be considered finished?

**Comment by zidad** [comment]
I have to fix the build, but didn't have enough time for it yet, sorry...

**Comment by CasperSJ** [comment]
Okay no worries, take your time. Do you have a rough estimate though?

**Comment by micdenny** [comment]
@zidad remember to get the latest changes on `develop` branch, as you see there's some commit (the grayed ones) that should be included in the master v1 release:

![image](https://user-images.githubusercontent.com/1633595/36202246-4b10ebb2-1183-11e8-83ae-f5ccc6e71b58.png)

**Comment by micdenny** [comment]
please follow the issue #67 to know when we will submit a v1 .net core standard version of easynetq management

**Comment by zidad** [comment]
@CasperSJ it's finally available on nuget now:
https://www.nuget.org/packages/easynetq.management.client
