### ISSUE TITLE
Fix the build for .NET Standard release

### ISSUE THREAD

**Issue by micdenny** [EasyNetQ/EasyNetQ.Management.Client#67]
@zidad said in #64 

> I have to fix the build, but didn't have enough time for it yet, sorry...

so we just lack the build to finish this porting, if anyone can help is appreciated, otherwise we wait for @zidad 

**while doing this, remember to get the latest changes on `develop` branch, as you see there's some commit (the grayed ones) that should be included in the master v1 release:**

![image](https://user-images.githubusercontent.com/1633595/36202246-4b10ebb2-1183-11e8-83ae-f5ccc6e71b58.png)

**Comment by luigiberrettini** [comment]
Sorry what do you mean by fix the build?
The build script based on cake is currently working

**Comment by zidad** [comment]
@luigiberrettini Yes, which is something @micdenny has to do, I don't have access to the nuget API keys.

**Comment by zidad** [comment]
@luigiberrettini build is on its way, sorry for the long delay, and thanks so much for your contribution:
https://ci.appveyor.com/project/EasyNetQ/easynetq-management-client

**Comment by zidad** [comment]
@luigiberrettini so the publish is succeeded, but we only get a 1.0.0 version of the package independent of the tag I pushed, am I doing something wrong with firing the build?

**Comment by luigiberrettini** [comment]
The build is ok but tags should follow the pattern `vX.Y.Z`
