### ISSUE TITLE
Publish EasyNetQ to www.nuget.org

### ISSUE THREAD

**Issue by DanielBryars** [EasyNetQ/EasyNetQ.Management.Client#69]
The latest version of EasyNetQ.Management.Client  (https://www.nuget.org/packages/EasyNetQ.Management.Client/) is version 0.52.0.188. This version looks pretty old even though it was published 3 months ago (for example it doesn't have the netStandard build, and it's missing some fields like Exclusive in Queue).

Please can you publish the latest build? 

Even better can you set it up to publish the latest version from GitHub on every successful build? If you give me access I'll give it a go.

**Comment by zidad** [comment]
sorry, this is long overdue. We have AppVeyor integration, I'm trying to release a build now.
https://ci.appveyor.com/project/EasyNetQ/easynetq-management-client

**Comment by DanielBryars** [comment]
Hi Zidad, no need to apologise! I can see the package 1.0.0 in Nuget now. Many thanks!!!
