### ISSUE TITLE
Branch usage is confusing and maintenance cost high

### ISSUE THREAD

**Issue by luigiberrettini** [EasyNetQ/EasyNetQ.Management.Client#70]
1. `feature/netcore` should be closed since it is merged in master
2. `develop` should be rebased on master then merged and closed
3. People should open PRs based on master that then get merged into master

**Comment by zidad** [comment]
Hi luigi, thanks a lot. Will have a look at it. I also have some issues merging master to develop (apparently there were some changes in there not included in your conversion branch, as I left it open too long). 

Are you interested in joining us as maintainer for this repo?

**Comment by luigiberrettini** [comment]
I think the PR @lsfera worked on and to which I contributed did not include the changes in the develop branch.
Is the purpose of that branch creating future improvements based on master or something else?

I am interested, but my contributions will be best effort since I do not have a lot of free time.

**Comment by zidad** [comment]
Thanks a lot! That free time issue is the same for all of us unfortunately :(

I wanted to merge master to develop, but there were conflicts that I couldn't solve easily. I think the changes from develop should be released to master ASAP so they don't diverge anymore. 

Your branch was released to master as I wanted a stable release out on nuget.

**Comment by luigiberrettini** [comment]
I suggest to follow this plan:

1. fix develop to include master changes and merge it to master
3. remove all branches except master
4. ask people to rebase PR on master
5. process each PR separately

**Comment by luigiberrettini** [comment]
If the feature/netcore branch is aligned with master can you please proceed to delete it?
Thanks!

**Comment by luigiberrettini** [comment]
1. Created #72 with commits from develop that can be merged to master
2. Please delete the feature/netcore branch
3. Please create a ack-mode branch: the last commit in develop needs some work to be performed since it introduces a breaking change that needs new Docker images and I would like to allow supporting also the old ack mode (I will submit a PR for the ack-mode branch so that the develop branch can be deleted)
