### ISSUE TITLE
Package signing

### ISSUE THREAD

**Issue by BatNiy** [EasyNetQ/EasyNetQ.Management.Client#96]
Hi,

On using assembly from nuget-repository I have exception like that:

> _An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll
> Could not load file or assembly 'EasyNetQ.Management.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)_

We sign our assemblies, so dependent assemblies also should be signed and have strong name.

Can you introduce assembly signing?

**Comment by micdenny** [comment]
This request occurs once every 1/2 years, it is not so requested and we didn’t want to maintain a certificate and the signing process, usually we suggest to fork the repo and do the signing yourself. 

We can re-consider it, but the certificate could become a PITA.

**Comment by lukebakken** [comment]
@BatNiy - just as a suggestion, you could always add a build step to sign the official assembly yourself ([link](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name)). No need to fork the project.

**Comment by micdenny** [comment]
Thanks @lukebakken to point that out, I don't know much about assembly signing.
