### ISSUE TITLE
GetQueueAsync : cannot deserialize JSON array into type EasyNetQ.Management.Client.Model.ChannelDetaile   (intermittent)

### ISSUE THREAD

**Issue by rkv5** [EasyNetQ/EasyNetQ.Management.Client#97]
There are intermittent failures of the method GetQueueAsync with the mentioned exception.

I found out that under the hood the method executes request to /api/queues
and the C# model which is mapped to response expects value of {"consumer_details":{"channel_details"  to be object. However, sometimes there is an array instead which yields deserialization error (see attached image with WireShark capture on the right). Not sure which side should actually handle this : EasyNetQ or RMQ Management API.

![channel_details_issue](https://user-images.githubusercontent.com/10196566/47724298-1230ec00-dc5f-11e8-8ac9-5ed1685cabe4.png)

**Comment by ninjaboy** [comment]
I can confirm that this is happening for me as well

**Comment by fsev** [comment]
Also happening for me - I see a PR has already been submitted for this but has not yet been approved/merged.
https://github.com/EasyNetQ/EasyNetQ.Management.Client/pull/95

**Comment by Pliner** [comment]
Fixed by #95 in [v1.1.0](https://www.nuget.org/packages/EasyNetQ.Management.Client/1.1.0)
