### ISSUE TITLE
Update Nuget package

### ISSUE THREAD

**Issue by jsaldukas** [EasyNetQ/EasyNetQ.Management.Client#98]
Hi,

With current management client (v1.0.0) GetMessagesFromQueueAsync doesn't work and returns BadRequest. I see there has been a fix:  50171d74746a7067d1bb20a6fc81a6ed5dcc375d , but Nuget package was not updated since then. Could you please create new nuget package with the fix included?

**Comment by JeroenMX** [comment]
Just bumped into the same problem. In order to continue using the package i need this fix.

**Comment by jsaldukas** [comment]
While not a clean solution at all, but as a temporary workaround you could copy GetMessagesCriteria into your code:

```csharp
private class GetMessagesCriteriaNew : GetMessagesCriteria
{
	public GetMessagesCriteriaNew(long count, Ackmodes ackmode) : base(count, true)
	{
		Ackmode = ackmode.ToString();
	}

	public string Ackmode { get; private set; }

	public enum Ackmodes
	{
		ack_requeue_false,
		ack_requeue_true,
		reject_requeue_false,
		reject_requeue_true
	}
}
```
and use it like this:
```csharp
// ...
var criteria = new GetMessagesCriteriaNew(1, GetMessagesCriteriaNew.Ackmodes.ack_requeue_false);
var messages = await managementClient.GetMessagesFromQueueAsync(errorQueue, criteria);
// ...
```

**Comment by JeroenMX** [comment]
Thanks a lot for that. I'll be using it until someone finds the time to release a new version.

**Comment by pmbanka** [comment]
I'd like to join this request, we just run into an issue that was already fixed in this commit https://github.com/EasyNetQ/EasyNetQ.Management.Client/commit/2ded2cc161fa1a849ca98ef987b5bf6f1973bc69

**Comment by Pliner** [comment]
Hi, sorry guys! The package was updated https://www.nuget.org/packages/EasyNetQ.Management.Client/1.1.0.
