### ISSUE TITLE
exchange names need escaping

### ISSUE THREAD

**Issue by mijabr** [EasyNetQ/EasyNetQ.Management.Client#99]
Seems DeleteBindingAsync() does not handle the case where source/destination has a colon in the name. I get a 404 when trying to delete. 

Examining the request I see

http://localhost:15672/api/bindings/%2F/e/My:Exchange1/e/My:Exchange1/~

but it should be

http://localhost:15672/api/bindings/%2F/e/My%3AExchange1/e/My%3AExchange1/~

Looks like an addition to SanitiseName() and include it DeleteBindingAsync() for source/destination names.

Can I give you a pull request for this?

**Comment by Pliner** [comment]
https://www.nuget.org/packages/EasyNetQ.Management.Client/2.0.0-beta3
